// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package cmd

import "bell/app"

// Injectors from wire.go:

func BuildApp(path *string) (*app.App, error) {


	return nil,nil
}